/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.MVector;
import Model.Vehicle;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.Timer;

/**
 *
 * @author pashathebeast
 */
public class MovementPanel extends javax.swing.JPanel {
    ArrayList<Vehicle> preys;
    Vehicle hunter;
    Timer m_timer;
    public static Point mouseLocation;
    MVector desiredVector;
    
    //MVector preys.get(i).getLocation();
    //MVector speed;
    int width;
    int height;
    float hue, saturation, luminance;
    Random r;
    /**
     * Creates new form MovementPanel
     */
    public MovementPanel() {
        initComponents();
        preys = new ArrayList();
        m_timer = new Timer(25, new TimerAction());
        r = new Random();
        desiredVector = new MVector();
        

    }
    
    @Override
    public void paint(Graphics g) {
        super.paint(g);   
        
        Graphics2D g2D = (Graphics2D)g;
        g2D.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        
        g2D.setColor(Color.LIGHT_GRAY);
        g2D.drawRect(40, 40, width-80, height-80);
        
        
        
        if (hunter != null) {
            g2D.setColor(Color.white);
            g2D.fill(hunter.getVehicleShape());
            g2D.setColor(Color.black);
            g2D.draw(hunter.getVehicleShape());
        }
        
        saturation = 0.9f;    //1.0 for brilliant, 0.0 for dull
        luminance = 1f;       //1.0 for brighter, 0.0 for black
        //for (Vehicle m : preys){
        for (int i = 0; i < preys.size(); i++) {
            g2D.setColor(Color.getHSBColor(preys.get(i).getHue(), saturation, luminance));
            g2D.fill(preys.get(i).getVehicleShape());
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAction = new javax.swing.JButton();
        labelAmount = new javax.swing.JLabel();
        buttonPlayPause = new javax.swing.JButton();
        labelHunter = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        buttonAction.setLabel("Action");
        buttonAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionActionPerformed(evt);
            }
        });

        buttonPlayPause.setText("play/pause");
        buttonPlayPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlayPauseActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(buttonAction)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(buttonPlayPause)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labelHunter))
                    .add(labelAmount))
                .addContainerGap(599, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(labelAmount)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 509, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(buttonAction)
                    .add(buttonPlayPause)
                    .add(labelHunter))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionActionPerformed

        height = this.getHeight();
        width = this.getWidth();
        
        if (hunter == null) {
            hunter = new Vehicle(new MVector(r.nextInt(width), r.nextInt(height)), new MVector(width, height));
            hunter.setScale(15);
            hunter.setMaxSpeed(5);
            hunter.setMaxForce(0.4);
        }
        
        
        // add preys
        for (int i = 0; i < 10; i++) {
            Vehicle v = new Vehicle(new MVector(r.nextInt(width-100)+50, r.nextInt(height-100)+50), new MVector(width, height)); 
            v.setMaxSpeed(4);
            v.setMaxForce(0.3);
            preys.add(v);
        }
        
        labelAmount.setText("Population size: " + preys.size());
        if (!m_timer.isRunning()) {
            m_timer.start();
        }

    }//GEN-LAST:event_buttonActionActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        MovementPanel.mouseLocation = this.getMousePosition();
        if (this.getMousePosition() != null) {
            //labelAmount.setText(String.format("(%d,%d)", (int)this.getMousePosition().getX(), (int)this.getMousePosition().getY()));
        }
        
    }//GEN-LAST:event_formMouseMoved

    private void buttonPlayPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlayPauseActionPerformed
        if (!m_timer.isRunning()) {
            m_timer.start();
        }
        else{
            m_timer.stop();
        }
    }//GEN-LAST:event_buttonPlayPauseActionPerformed

        class TimerAction implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            
            int preyToHunt = 1;
            double distance = 10000;
            MVector distVector;
            for (int i = 0; i < preys.size(); i++) {
                
                distVector = new MVector(hunter.getLocation().getX() - preys.get(i).getLocation().getX(), hunter.getLocation().getY() - preys.get(i).getLocation().getY());
                
                // finding what prey to hunt
                if (distVector.getLength() < distance) {
                    distance = distVector.getLength();
                    preyToHunt = i;
                }
                

                
                // now look at the boundaries
                
                if(!preys.get(i).KeepInsideBoundaries())
                {
                    // looking whether a prey should flee from hunter
                    if (distVector.getLength() < 30 + hunter.getScale() ) {
                        preys.get(i).Flee(hunter.getLocation());
                    }
                    else{
                        if (distVector.getLength() < 300 + hunter.getScale() ) {
                            preys.get(i).Flee(hunter.getLocation());
                            preys.get(i).Wander();
                        }
                        else{
                            preys.get(i).Wander();
                        }
                    }
                    
                }
   
                preys.get(i).Update();
                
                
            }
            
            if (!preys.isEmpty()) {
                if (!hunter.KeepInsideBoundaries()) {
                    hunter.Seek(new MVector(preys.get(preyToHunt).getLocation().getX(),preys.get(preyToHunt).getLocation().getY()));
                }
                
                
                if (hunter.getVehicleShape().intersects(preys.get(preyToHunt).getVehicleShape().getBounds2D())) {
                    preys.remove(preyToHunt);
                    labelAmount.setText("Population size: " + preys.size());
                    hunter.setScale(hunter.getScale() + 0.1);
                    hunter.setMaxForce(hunter.getMaxForce() * 0.99);
                    hunter.setMaxSpeed(hunter.getMaxSpeed() * 0.99);
                }
                else{
                    hunter.setScale(hunter.getScale() - 0.002);
                    hunter.setMaxForce(hunter.getMaxForce() * 1.0002);
                    hunter.setMaxSpeed(hunter.getMaxSpeed() * 1.0002);
                }
            }
            else{
                if (!hunter.KeepInsideBoundaries()) {
                    hunter.Wander();
                }
            }
            
            
            hunter.Update();
            UpdateHunterLabels();
            repaint();
            //Point mouseLocation = MouseInfo.getPointerInfo().getLocation();
            //for (Vehicle m : preys){
                //m.Arrive(new MVector((int)MovementPanel.mouseLocation.getX(), (int)MovementPanel.mouseLocation.getY()));
                //m.Wander();
                //System.out.print(String.format("(%d,%d)", (int)desiredVector.getX(), (int)desiredVector.getY()));
            //}
        }
    }
     private void UpdateHunterLabels(){
         labelHunter.setText(String.format("Hunter maxspeed: %f, agility: %f, scale: %f", hunter.getMaxSpeed(), hunter.getMaxForce(), hunter.getScale()));
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAction;
    private javax.swing.JButton buttonPlayPause;
    private javax.swing.JLabel labelAmount;
    private javax.swing.JLabel labelHunter;
    // End of variables declaration//GEN-END:variables
}
